name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
    - name: Build with Jekyll
      run: |
        gem install jekyll bundler
        bundle exec jekyll build
    - name: Test with HTMLProofer
      run: |
        gem install html-proofer
        htmlproofer ./_site --check-html --check-img-http --disable-external